SoftGop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.contrib.auth.decorators import login_required

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),

    path('contractors/', include('contractor.urls', namespace='contractor')),
    path('works/', include('work.urls', namespace='work')),
    path('penaltys/', include('penalty.urls', namespace='penalty')),
    path('', include('account.urls', namespace='account')),
    path('inicio', login_required(TemplateView.as_view(template_name='index.html')), name='index')
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

account/urls.py
from django.urls import path

from .views import AccountCreate, AccountList, LoginView, LogoutView,AccountUpdate,AccountDelete


app_name = 'account'

urlpatterns = [
    path('', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('list/', AccountList.as_view(), name='list'),
    path('create/', AccountCreate.as_view(), name='create'),
    path('update/<int:pk>/', AccountUpdate.as_view(), name='update'),
    path('delete/<int:pk>/', AccountDelete.as_view(), name='delete'),
]

work/urls.py
from django.urls import path

from .views import WorkValidList, WorkFinishedList, WorkExpiredList, WorkCreate, WorkDelete, WorkUpdate, WorkFinish
from .reports.work import ReportWorkView

app_name = 'work'
urlpatterns = [
    path('', WorkValidList.as_view(), name='list-vigentes'),
    path('expired/', WorkExpiredList.as_view(), name='list-exprired'),
    path('finished/', WorkFinishedList.as_view(), name='list-finished'),
    path('create/', WorkCreate.as_view(), name='create'),
    path('delete/<int:pk>/', WorkDelete.as_view(), name='delete'),
    path('update/<int:pk>/', WorkUpdate.as_view(), name='update'),
    path('finish/<int:pk>/', WorkFinish.as_view(), name='finish'),
    path('report/<int:pk>/', ReportWorkView.as_view(), name='report'),
]

account/models.py
from django.db import models

# Create your models here.

account/forms.py
import re
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError


class RegistroForm(UserCreationForm):
    error_css_class = 'is-invalid'

    fields_only_letters = [
    ]

    fields_required = [
        'first_name', 'last_name',
        'email'

    ]

    class Meta:
        model = User
        fields = [
            'username',
            'first_name',
            'last_name',
            'email',
            #'is_staff',
        ]

        labels = {
            'username':'Nombre de usuario',
        }

        help_texts = {
            'username':'',
            'first_name': 'Ingresar solo letras',
            'last_name': 'Ingresar solo letras',
            'email': 'Ingresar un formato correcto',
        }

    def __init__(self, *args, **kwargs):
        super(RegistroForm, self).__init__(*args, **kwargs)

        self.fields['first_name'].required = True
        self.fields['last_name'].required = True
        self.fields['email'].required = True
        
        for visible in self.visible_fields():
            attrs = {'class': 'form-control', 'placeholder': visible.label}

            if visible.name in self.fields_only_letters:
                attrs.update({'pattern': "[-a-zA-Z_]+"})

            visible.field.widget.attrs.update(attrs)

            if self.errors.get(visible.name, None):
                visible.field.widget.attrs.update({'class': 'form-control is-invalid'})

account/views.py
from django.shortcuts import render

from django.conf import settings
from django.shortcuts import redirect
from django.contrib.auth.models import User
from django.views.generic import ListView,CreateView,UpdateView,DeleteView
from django.contrib.auth import views as auth_views
from django.contrib.auth.mixins import LoginRequiredMixin

from django.urls import reverse_lazy

from .forms import RegistroForm


# if not request.user.is_authenticated:
#         return redirect('%s?next=%s' % (settings.LOGIN_URL, request.path))

class LoginView(auth_views.LoginView):
    redirect_authenticated_user = True


class LogoutView(auth_views.LogoutView):
    pass


class AccountList(LoginRequiredMixin, ListView):
    model = User
    template_name = "accounts/index.html"


class AccountCreate(LoginRequiredMixin, CreateView):
    template_name = "accounts/create.html"
    success_url = reverse_lazy("account:list")
    form_class = RegistroForm
    model = User

class AccountUpdate(LoginRequiredMixin, UpdateView):
    model = User
    form_class = RegistroForm
    success_url = reverse_lazy('account:list')
    template_name = 'accounts/update.html'

class AccountDelete(LoginRequiredMixin, DeleteView):
    model = User
    success_url = reverse_lazy('account:list')
    template_name = 'accounts/delete.html'

templates/accounts/create.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div id="content-wrapper">
    <h1>Agregar operario <a class="fas fa-fw fa-list-ul" href="{% url 'account:list' %}"></a></h1><br><br>
    <form class="central_container_form needs-validation was-validated" action="{% url 'account:create' %}"
        method="POST">
        {% csrf_token %}
        {% for hidden in form.hidden_fields %}
                {{ hidden }}
                {% endfor %}
                {% for field in form.visible_fields %}
                    <div class="form-group">
                        {{ field }}
                        {% if field.help_text %}<small class="form-text text-muted">{{ field.help_text }}</small>{% endif %}
                        {% for error in field.errors %}
                            <div class="invalid-feedback">
                                {{ error }}
                            </div>
                        {% endfor %}
                    </div>
                {% endfor %}
        <div class="modal-footer">
            <button id="IdAgregar" class="btn btn-primary" type="submit">Agregar</button>
            <a href="{% url 'account:list' %}" class="btn btn-secondary">Cancelar</a>
        </div>
    </form>
</div>
{% endblock content %}

{% block js %}
{{ block.super }}
<script src="{% static '/js/sb-admin.min.js' %}"></script>
{% endblock js %}

<!--
    <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="form-group">
                    <label>Nombre</label>
                    <input class="form-control" type="text" name="first_name">
                </div>
            </div>
        </div>
    -->

templates/accounts/delete.html
0{% extends "base.html" %}
{% load static %}

{% block content %}

<div id="content-wrapper">
    <h1>Desea eliminar el contratista:</h1>
    <br>
    <div class="central_container_form">
        <ul class="list-group list-group-flush">
                <li class="list-group-item">Nombre de usuario: {{ object.username }}</li>
                <li class="list-group-item">Nombre: {{ object.first_name }}</li>
                <li class="list-group-item">Apellido: {{ object.last_name }}</li>
                <li class="list-group-item">Correo electronico: {{ object.email }}</li>
                <li class="list-group-item">Admistrador: {{ object.is_staff }}</li>
        </ul>

        <form action="{% url 'account:delete' object.id %}" method="post">
            {% csrf_token %}
            <div class="modal-footer">
                <a href="#EliminarModal-{{ account.id }}" class="btn btn-danger" data-toggle="modal">
                    Eliminar
                </a>                
                <a href="{% url 'account:list' %}" class="btn btn-secondary">Cancelar</a>                
            </div>

            <div class="modal fade" id="EliminarModal-{{ account.id }}" tabindex="-1" role="dialog"
                aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Eliminar el operario: {{ object.first_name }}</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <p>Si elimina este contrastista sus datos se perderan definitivamente. ¿Esta seguro?</p>
                        </div>
                        <div class="modal-footer">                                
                            <button class="btn btn-danger" type="submit">Eliminar</button>
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                        </div>
                    </div>
                </div>
            </div>


        </form>
    </div>
</div>
{% endblock content %}

{% block js %}
{{ block.super }}
<script src="{% static '/js/sb-admin.min.js' %}"></script>
{% endblock js %}

templates/accounts/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div id="content-wrapper">
    <h1>Operarios <a class="fas fa-fw fa-plus-circle" href="{% url 'account:create' %}"></a></h1><br><br>
    <div id="accordion" class="accordion central_container_accordion">
        {% for account in object_list %}
        <div class="card">
            <div class="card-header" id="heading-{{ account.id }}">
                <h5 class="mb-0" data-toggle="collapse" data-target="#collapse-{{ account.id }}" aria-expanded="true"
                    aria-controls="collapse-{{ account.id }}">
                    {{ account.first_name}} {{account.last_name}}
                </h5>
            </div>

            <div id="collapse-{{ account.id }}" class="collapse {% if forloop.first %}show{% endif %}"
                aria-labelledby="heading-{{ account.id }}" data-parent="#accordion">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">Nombre de usuario: {{ account.username }}</li>
                    <li class="list-group-item">Nombre: {{ account.first_name }}</li>
                    <li class="list-group-item">Apellido: {{ account.last_name }}</li>
                    <li class="list-group-item">Correo electronico: {{ account.email }}</li>
                    <li class="list-group-item">Admistrador: {{ account.is_staff }}</li>
                    
                </ul>
                <div class="card-body">
                    <a href="{% url 'account:update' account.id %}" class="btn btn-primary">Modificar</a>
                    <a href="{% url 'account:delete' account.id %}" class="btn btn-danger">Eliminar</a>
                </div>
            </div>
        </div>
        {% empty %}
        <div class="jumbotron jumbotron-fluid">
            <div class="container">
                <h1 class="display-4">No se han encontrado datos.</h1>
                <p class="lead">Verifique haber creado operador o admistrador antes.</p>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock content %}

{% block js %}
{{ block.super }}
{% endblock js %}

templates/accounts/update.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div id="content-wrapper">
    <h1>Modificar operario <a class="fas fa-fw fa-list-ul" href="{% url 'account:list' %}"></a></h1><br><br>
    <form class="central_container_form needs-validation was-validatedx"
        action="{% url 'account:update' object.id %}" method="POST">
        {% csrf_token %}
        {% for hidden in form.hidden_fields %}
        {{ hidden }}
        {% endfor %}
        {% for field in form.visible_fields %}
        <div class="form-group">
            {{ field.label_tag }}
            {{ field }}
            {% for error in field.errors %}
            <div class="invalid-feedback">
                {{ error }}
            </div>
            {% endfor %}
        </div>
        {% endfor %}
        <div class="modal-footer">
            <a href="#ModificarModal-{{ account.id }}" class="btn btn-primary" data-toggle="modal">
                Modificar
            </a>
            <a href="{% url 'account:list' %}" class="btn btn-secondary">Cancelar</a>
        </div>

        <div class="modal fade" id="ModificarModal-{{ account.id }}" tabindex="-1" role="dialog"
            aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Modificar el operario: {{ object.first_name }}</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <p>¿Esta seguro de Modificar este operardor?</p>
                    </div>
                    <div class="modal-footer">                        
                        <button type="submit" class="btn btn-primary">Aceptar</button>
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock content %}

{% block js %}
{{ block.super }}
<script src="{% static '/js/sb-admin.min.js' %}"></script>
{% endblock js %}