SoftGop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.contrib.auth.decorators import login_required

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),

    path('contractors/', include('contractor.urls', namespace='contractor')),
    path('works/', include('work.urls', namespace='work')),
    path('penaltys/', include('penalty.urls', namespace='penalty')),
    path('', include('account.urls', namespace='account')),
    path('inicio', login_required(TemplateView.as_view(template_name='index.html')), name='index')
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

penalty/urls.py
from django.urls import path

from .views import PenaltyList, PenaltyCreate, PenaltyDelete, PenaltyUpdate

app_name = 'penalty'
urlpatterns = [
    path('', PenaltyList.as_view(), name='list'),
    path('create/', PenaltyCreate.as_view(), name='create'),
    path('delete/<int:pk>/', PenaltyDelete.as_view(), name='delete'),
    path('update/<int:pk>/', PenaltyUpdate.as_view(), name='update')
]

work/urls.py
from django.urls import path

from .views import WorkValidList, WorkFinishedList, WorkExpiredList, WorkCreate, WorkDelete, WorkUpdate, WorkFinish
from .reports.work import ReportWorkView

app_name = 'work'
urlpatterns = [
    path('', WorkValidList.as_view(), name='list-vigentes'),
    path('expired/', WorkExpiredList.as_view(), name='list-exprired'),
    path('finished/', WorkFinishedList.as_view(), name='list-finished'),
    path('create/', WorkCreate.as_view(), name='create'),
    path('delete/<int:pk>/', WorkDelete.as_view(), name='delete'),
    path('update/<int:pk>/', WorkUpdate.as_view(), name='update'),
    path('finish/<int:pk>/', WorkFinish.as_view(), name='finish'),
    path('report/<int:pk>/', ReportWorkView.as_view(), name='report'),
]

penalty/models.py
from django.db import models

# Create your models here.

class Penalty(models.Model):
    nombre = models.CharField(max_length=60)

    porcentaje_valor_multa = models.IntegerField()
    
    porcentaje_desfase = models.IntegerField()

    porcentaje_valor_desfase = models.IntegerField()

    def __str__(self):
        return self.nombre

penalty/forms.py
import re
from django.forms import ModelForm
from django.core.exceptions import ValidationError

from .models import Penalty



class PenaltyForm(ModelForm):
    error_css_class = 'is-invalid'

    fields_only_letters = [
        'nombre'
    ]

    class Meta:
        model = Penalty
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(PenaltyForm, self).__init__(*args, **kwargs)

        for visible in self.visible_fields():
            attrs = {'class': 'form-control', 'placeholder': visible.label}
            if visible.name in self.fields_only_letters:
                attrs.update({'pattern': "[-a-zA-Z_]+"})

            visible.field.widget.attrs.update(attrs)

            if self.errors.get(visible.name, None):
                visible.field.widget.attrs.update({'class': 'form-control is-invalid'})

penalty/views.py
from django.views.generic import ListView, CreateView, DeleteView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy

from .models import Penalty
from .forms import PenaltyForm
# Create your views here.

class PenaltyList(LoginRequiredMixin, ListView):
    model = Penalty
    template_name = "penalty/index.html"

class PenaltyCreate(LoginRequiredMixin, CreateView):
    model = Penalty
    form_class = PenaltyForm
    success_url = reverse_lazy('penalty:list')
    template_name = 'penalty/form.html'

class PenaltyDelete(LoginRequiredMixin, DeleteView):
    model = Penalty
    success_url = reverse_lazy('penalty:list')
    template_name = 'penalty/delete.html'

class PenaltyUpdate(LoginRequiredMixin, UpdateView):
    model = Penalty
    form_class = PenaltyForm
    success_url = reverse_lazy('penalty:list')
    template_name = 'Penalty/update.html'

templates/penalty/delete.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div id="content-wrapper">
    <h1>Desea eliminar el tipo de regla:</h1>
    <br>
    <!--<h3 class="blockquote text-center">{{ object.nombre_completo}} {{object.documento_identidad}}</h3>-->
    <div class="central_container_form">
        <ul class="list-group list-group-flush">
            <li class="list-group-item">Nombre : {{ penalty.nombre }}</li>
            <li class="list-group-item">Porcentaje valor multa: {{ penalty.porcentaje_valor_multa }}</li>
            <li class="list-group-item">Porcentaje desfase: {{ penalty.porcentaje_desface }}</li>
            <li class="list-group-item">Porcentaje valor desfase: {{ penalty.porcentaje_valor_desface }}</li>
        </ul>

        <form action="{% url 'penalty:delete' object.id %}" method="post">
            {% csrf_token %}
            <div class="modal-footer">
                <a href="#EliminarModal-{{ penalty.id }}" class="btn btn-danger" data-toggle="modal">Eliminar</a> 
                <a href="{% url 'penalty:list' %}" class="btn btn-secondary">Cancelar</a>
            </div>

            <div class="modal fade" id="EliminarModal-{{ penalty.id }}" tabindex="-1" role="dialog"
                aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Eliminar la multa: {{ penalty.nombre}}</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <p>Si elimina esta multa sus datos se perderan definitivamente. ¿Esta seguro?</p>
                        </div>
                        <div class="modal-footer">
                            <button class="btn btn-danger" type="submit">Eliminar</button>
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

{% block js %}
{{ block.super }}
<script src="{% static '/js/sb-admin.min.js' %}"></script>
{% endblock js %}

templates/penalty/form.html
{% extends "base.html" %}
{% load static %}

{% block title %}Create {{ block.super }}{% endblock title %}

{% block content %}
    <div id="content-wrapper">
        <h1>Agregar reglas <a class="fas fa-fw fa-list-ul" href="{% url 'penalty:list' %}"></a></h1><br><br>
        <form class="central_container_form needs-validation was-validated" action="{% url 'penalty:create' %}"" method="POST">
            {% csrf_token %}
                {% for hidden in form.hidden_fields %}
                {{ hidden }}
                {% endfor %}
                {% for field in form.visible_fields %}
                    <div class="form-group">
                        {{ field }}
                        {% if field.help_text %}<small class="form-text text-muted">{{ field.help_text }}</small>{% endif %}
                        {% for error in field.errors %}
                            <div class="invalid-feedback">
                                {{ error }}
                            </div>
                        {% endfor %}
                    </div>
                {% endfor %}
            <div class="modal-footer">
                <button id = "IdAgregar" class="btn btn-primary" type="submit">Agregar</button>
                <a href="{% url 'penalty:list' %}"
                    class="btn btn-secondary">Cancelar</a>
                <!--<a class="btn btn-primary" href="Login.html">Agregar</a>-->
            </div>
        </form>
    </div>
{% endblock content %}

{% block js %}
    {{ block.super }}
    <script src="{% static '/js/sb-admin.min.js' %}"></script>
{% endblock js %}

templates/penalty/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <div id="content-wrapper">
        <h1>Reglas <a class="fas fa-fw fa-plus-circle" href="{% url 'penalty:create' %}"></a></h1><br><br>
        <div id="accordion" class="accordion central_container_accordion">
            {% for penalty in object_list%}
                <div class="card">
                    <div class="card-header" id="heading-{{ penalty.id }}">
                        <h5 class="mb-0"
                            data-toggle="collapse"
                            data-target="#collapse-{{ penalty.id }}"
                            aria-expanded="true"
                            aria-controls="collapse-{{ penalty.id }}">
                            {{ penalty.nombre }}
                        </h5>
                    </div>

                    <div id="collapse-{{ penalty.id }}" class="collapse {% if forloop.first %}show{% endif %}" aria-labelledby="heading-{{ contractor.id }}" data-parent="#accordion" >
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item">Nombre : {{ penalty.nombre }}</li>
                            <li class="list-group-item">Porcentaje valor multa: {{ penalty.porcentaje_valor_multa }}</li>
                            <li class="list-group-item">Porcentaje desfase: {{ penalty.porcentaje_desfase }}</li>
                            <li class="list-group-item">Porcentaje valor desfase: {{ penalty.porcentaje_valor_desfase }}</li>
                        </ul>
                        <div class="card-body">
                            <a href="{% url 'penalty:update' penalty.id %}" 
                                class="btn btn-primary">Modificar</a>
                            <a href="{% url 'penalty:delete' penalty.id %}"
                                class="btn btn-danger">Eliminar</a>                      
                        </div>
                    </div>

                </div>
                
            
            {% empty %}
                <div class="jumbotron jumbotron-fluid">
                    <div class="container">
                        <h1 class="display-4">No se han encontrado datos.</h1>
                        <p class="lead">Verifique haber creado una regla antes.</p>
                    </div>
                </div>
            {% endfor%}
        </div>
    </div>
{% endblock content %}

{% block modals %}
    {{ block.super }}
    <div class="modal fade" id="AgreeModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="button" >
                <div class="modal-content">

                </div>
            </div>
        </div>
{% endblock modals %}

{% block js %}
    {{ block.super }}
    <script src="{% static '/js/sb-admin.min.js' %}"></script>
{% endblock js %}

templates/penalty/update.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div id="content-wrapper">
    <h1>Modificar regla <a class="fas fa-fw fa-list-ul" href="{% url 'penalty:list' %}"></a></h1><br><br>
    <form class="central_container_form needs-validation was-validatedx" action="{% url 'penalty:update' object.id %}"
        method="POST">
        {% csrf_token %}
        {% for hidden in form.hidden_fields %}
        {{ hidden }}
        {% endfor %}
        {% for field in form.visible_fields %}
        <div class="form-group">
            {{ field.label_tag }}
            {{ field }}
            {% for error in field.errors %}
            <div class="invalid-feedback">
                {{ error }}
            </div>
            {% endfor %}
        </div>
        {% endfor %}
        <div class="modal-footer">
            <a href="#ModificarModal-{{ penalty.id }}" class="btn btn-primary" data-toggle="modal">Modificar</a>
            <a href="{% url 'penalty:list' %}" class="btn btn-secondary">Cancelar</a>
        </div>

        <div class="modal fade" id="ModificarModal-{{ penalty.id }}" tabindex="-1" role="dialog"
            aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Modificar la multa: {{ penalty.nombre }}</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <p>¿Esta seguro de modificar esta multa?</p>
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-primary">Aceptar</button>
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock content %}

{% block js %}
{{ block.super }}
<script src="{% static '/js/sb-admin.min.js' %}"></script>
{% endblock js %}