SoftGop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.contrib.auth.decorators import login_required

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),

    path('contractors/', include('contractor.urls', namespace='contractor')),
    path('works/', include('work.urls', namespace='work')),
    path('penaltys/', include('penalty.urls', namespace='penalty')),
    path('', include('account.urls', namespace='account')),
    path('inicio', login_required(TemplateView.as_view(template_name='index.html')), name='index')
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

account/urls.py
from django.urls import path

from .views import AccountCreate, AccountList, LoginView, LogoutView,AccountUpdate,AccountDelete


app_name = 'account'

urlpatterns = [
    path('', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('list/', AccountList.as_view(), name='list'),
    path('create/', AccountCreate.as_view(), name='create'),
    path('update/<int:pk>/', AccountUpdate.as_view(), name='update'),
    path('delete/<int:pk>/', AccountDelete.as_view(), name='delete'),
]

work/urls.py
from django.urls import path

from .views import WorkValidList, WorkFinishedList, WorkExpiredList, WorkCreate, WorkDelete, WorkUpdate, WorkFinish
from .reports.work import ReportWorkView

app_name = 'work'
urlpatterns = [
    path('', WorkValidList.as_view(), name='list-vigentes'),
    path('expired/', WorkExpiredList.as_view(), name='list-exprired'),
    path('finished/', WorkFinishedList.as_view(), name='list-finished'),
    path('create/', WorkCreate.as_view(), name='create'),
    path('delete/<int:pk>/', WorkDelete.as_view(), name='delete'),
    path('update/<int:pk>/', WorkUpdate.as_view(), name='update'),
    path('finish/<int:pk>/', WorkFinish.as_view(), name='finish'),
    path('report/<int:pk>/', ReportWorkView.as_view(), name='report'),
]

templates/components/navbar.html
<ul class="sidebar navbar-nav">
    {% url 'index' as index %}
    <li class="nav-item {% if request.path == index %}active{% endif %}">
        <a class="nav-link" href="{{ index }}">
            <i class="fas fa-fw fa-home"></i>
            &nbsp; &nbsp;
            <span>Inicio</span>
        </a>
    </li>

    {% url 'contractor:list' as contractor_list %}
    <li class="nav-item {% if request.path == contractor_list %}active{% endif %}">
        <a class="nav-link" href="{{ contractor_list }}">
            <i class="fas fa-fw fa-user-circle"></i>
            &nbsp; &nbsp;
            <span>Contratistas</span>
        </a>
    </li>
    {% if request.user.is_staff %}    
        {% url 'account:list' as account_list %}
        <li class="nav-item {% if request.path == account_list %}active{% endif %}">
            <a class="nav-link" href="{{ account_list }}">
                <i class="fas fa-fw fa-user-circle"></i>
                &nbsp; &nbsp;
                <span>Operarios</span>
            </a>
        </li>
    {% endif %}

    <li class="nav-item {% if 'works' in request.path %}active{% endif %}">
        <div class="dropdown">
            <a class="nav-link">
    
                <i class="fas fa-fw fa-folder"></i>
                <span class="dropbtn">Contratos</span>
                <span class="fas fa-caret-down"></span>
    
                <div class="dropdown-content">
    
                    <a href="{% url 'work:list-vigentes' %}">Contratos al día</a><br>
                    <a href="{% url 'work:list-exprired' %}">Contratos con multas</a><br>
                    <a href="{% url 'work:list-finished' %}">Contratos terminados </a><br>
                    
                </div>
        </div>
    </li>
    
    {% if request.user.is_staff %}
        {% url 'penalty:list' as penalty_list %}
        <li class="nav-item {% if request.path == penalty_list %}active{% endif %}">
            <a class="nav-link" href="{{ penalty_list }}">
            <i class="fas fa-fw fa-chart-area"></i>
            &nbsp; &nbsp;
            <span>Reglas</span></a>
        </li>
    {% endif %}
    
    <!--<li class="nav-item">
        <a class="nav-link" href="#">
        <i class="fas fa-fw fa-table"></i>
        &nbsp; &nbsp;
        <span>Informes</span></a>
    </li>-->
</ul>