SoftGop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.contrib.auth.decorators import login_required

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),

    path('contractors/', include('contractor.urls', namespace='contractor')),
    path('works/', include('work.urls', namespace='work')),
    path('penaltys/', include('penalty.urls', namespace='penalty')),
    path('', include('account.urls', namespace='account')),
    path('inicio', login_required(TemplateView.as_view(template_name='index.html')), name='index')
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

work/urls.py
from django.urls import path

from .views import WorkValidList, WorkFinishedList, WorkExpiredList, WorkCreate, WorkDelete, WorkUpdate, WorkFinish
from .reports.work import ReportWorkView

app_name = 'work'
urlpatterns = [
    path('', WorkValidList.as_view(), name='list-vigentes'),
    path('expired/', WorkExpiredList.as_view(), name='list-exprired'),
    path('finished/', WorkFinishedList.as_view(), name='list-finished'),
    path('create/', WorkCreate.as_view(), name='create'),
    path('delete/<int:pk>/', WorkDelete.as_view(), name='delete'),
    path('update/<int:pk>/', WorkUpdate.as_view(), name='update'),
    path('finish/<int:pk>/', WorkFinish.as_view(), name='finish'),
    path('report/<int:pk>/', ReportWorkView.as_view(), name='report'),
]

work/models.py
from django.db import models
from contractor.models import Contractor
from penalty.models import Penalty

from .managers import WorkManager


class Work(models.Model):
    nombre= models.CharField(
        max_length=60, 
        unique=True,
        help_text="Ingresar solo letras")

    direccion = models.CharField(
        max_length=30)
        
    tipo = models.CharField(
        max_length=15,
        help_text="Ingresar solo letras")

    valor = models.IntegerField(
        help_text="Ingresar solo números")
    
    multa = models.IntegerField(default=0)

    fecha_de_inicio = models.DateField(
        help_text="Ingresar la fecha dd MM yy")

    fecha_de_fin = models.DateField(
        help_text="Ingresar la fecha dd MM yy")

    estado = models.BooleanField(
        "Activo", 
        default=True)

    contratista = models.ForeignKey(
        Contractor, 
        on_delete=models.CASCADE,
        help_text="Ingrese nombre del contratista encargado")

    reglas = models.ForeignKey(
        Penalty, 
        on_delete=models.CASCADE,
        help_text="Ingrese los porcentajes de multa")


    objects = models.Manager()
    estados = WorkManager()


    def mostrar_estado(self):
        if self.estado:
            mostrar_estado = "Activo"
        else:
            mostrar_estado = "Inactivo"
        
        return mostrar_estado

    def __str__(self):
        cadena = "{0}, {1}"
        return cadena.format(
            self.nombre, 
            self.direccion)

    def finalizar(self):
        if self.estado:
            self.estado = False
            self.save(update_fields=['estado'])

    def valor_multa(self, multa):
        if multa > 0:
            self.multa = multa
            self.save(update_fields=['multa'])

work/forms.py
import re
from django.forms import ModelForm
from django.core.exceptions import ValidationError

from .models import Work

class WorkForm(ModelForm):
    error_css_class = 'is-invalid'

    fields_only_letters = [
        'tipo'
    ]

    class Meta:
        model = Work
        fields = '__all__'
        exclude = ('estado', 'multa')

    
    def __init__(self, *args, **kwargs):
        super(WorkForm, self).__init__(*args, **kwargs)

        for visible in self.visible_fields():
            attrs = {'class': 'form-control', 'placeholder': visible.label}
            if visible.name in self.fields_only_letters:
                attrs.update({'pattern': "[-a-zA-Z_]+"})
            
            if visible.name == 'fecha_de_inicio':
                attrs.update()

            visible.field.widget.attrs.update(attrs)

            if self.errors.get(visible.name, None):
                visible.field.widget.attrs.update({'class': 'form-control is-invalid'})


class WorkFinishForm(ModelForm):
    class Meta:
        model = Work
        fields = ('estado',)
    

work/views.py
from django.views.generic import ListView, CreateView, DeleteView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin

from django.urls import reverse_lazy

from .models import Work
from .forms import WorkForm, WorkFinishForm
from .utils import calcular_multa


class WorkValidList(LoginRequiredMixin, ListView):
    model = Work
    template_name = "Works/index.html"
    queryset = Work.estados.valids()


class WorkExpiredList(LoginRequiredMixin, ListView):
    model = Work
    template_name = "Works/index.html"
    queryset = Work.estados.expireds()

    def get_queryset(self):
        queryset = super(WorkExpiredList, self).get_queryset()

        for query in queryset:
        
            multa = calcular_multa(query)
            query.valor_multa(multa)

        return queryset


class WorkFinishedList(LoginRequiredMixin, ListView):
    model = Work
    template_name = "Works/index.html"
    queryset = Work.estados.finisheds()


class WorkCreate(LoginRequiredMixin, CreateView):
    model = Work
    form_class = WorkForm
    success_url = reverse_lazy('work:list-vigentes')
    template_name = 'works/form.html'


class WorkDelete(LoginRequiredMixin, DeleteView):
    model = Work
    success_url = reverse_lazy('work:list-vigentes')
    template_name = 'works/delete.html'


class WorkUpdate(LoginRequiredMixin, UpdateView):
    model = Work
    form_class = WorkForm
    success_url = reverse_lazy('work:list-vigentes')
    template_name = 'works/update.html'


class WorkFinish(LoginRequiredMixin, UpdateView):
    model = Work
    form_class = WorkFinishForm
    success_url = reverse_lazy('work:list-finished')
    template_name = 'works/update.html'

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.finalizar()
        form = self.get_form()
        return self.form_valid(form)

templates/works/delete.html
{% extends "base.html" %}
{% load static %}


{% block content %}

<div id="content-wrapper">
    <h1>Desea eliminar el contrato:</h1>
    <br>
    <!--<h3 class="blockquote text-center">{{ object.nombre_completo}} {{object.documento_identidad}}</h3>-->
    <div class="central_container_form">
        <ul class="list-group list-group-flush">
            <li class="list-group-item">Nombre de la obra: {{ work.nombre }}</li>
            <li class="list-group-item">Dirección: {{ work.direccion }}</li>
            <li class="list-group-item">Tipo de obra: {{ work.tipo }}</li>
            <li class="list-group-item">Valor: {{ work.valor }}</li>
            <li class="list-group-item">Fecha de inicio: {{ work.fecha_de_inicio }}</li>
            <li class="list-group-item">Fecha de fin: {{ work.fecha_de_fin }}</li>
            <li class="list-group-item">Estado: {{ work.mostrar_estado }}</li>
            <li class="list-group-item">Contratista: {{ work.contratista }}</li>
        </ul>

        <form action="{% url 'work:delete' object.id %}" method="post">
            {% csrf_token %}
            <div class="modal-footer">
                    <a href="#EliminarModal-{{ work.id }}" class="btn btn-danger" data-toggle="modal">
                            Eliminar
                        </a>
                <a href="{% url 'work:list-vigentes' %}" class="btn btn-secondary">Cancelar</a>
            </div>

            <div class="modal fade" id="EliminarModal-{{ work.id }}" tabindex="-1" role="dialog"
                aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Eliminar el contrato: {{ work.nombre}}</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <p>Si elimina este contrato sus datos se perderan definitivamente. ¿Esta seguro?</p>
                        </div>
                        <div class="modal-footer">
                            <button class="btn btn-danger" type="submit">Eliminar</button>
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

{% block js %}
{{ block.super }}
<script src="{% static '/js/sb-admin.min.js' %}"></script>
{% endblock js %}

templates/works/form.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <div id="content-wrapper">
        <h1>Agregar contrato <a class="fas fa-fw fa-list-ul" href="{% url 'work:list-vigentes' %}"></a></h1><br><br>
        <form class="central_container_form needs-validation was-validated" action="{% url 'work:create' %}" method="POST">
            {% csrf_token %}
                {% for hidden in form.hidden_fields %}
                {{ hidden }}
                {% endfor %}
                {% for field in form.visible_fields %}                    
                    <div class="form-group">
                        {{ field }}
                        {% if field.help_text %}<small class="form-text text-muted">{{ field.help_text }}</small>{% endif %}
                        {% for error in field.errors %}
                            <div class="invalid-feedback">
                                {{ error }}
                            </div>
                        {% endfor %}
                    </div>
                {% endfor %}
            <div class="modal-footer">
                <button class="btn btn-primary" type="submit">Agregar</button>
                <a href="{% url 'work:list-vigentes' %}"
                    class="btn btn-secondary">Cancelar</a>
            </div>
        </form>
    </div>
{% endblock content %}

{% block js %}
    {{ block.super }}
    <script src="{% static '/js/sb-admin.min.js' %}"></script>
     
    <script type="text/javascript">
        function sumar_noches(fecha, noches) {

            if (!(fecha instanceof Date)) {
                fecha = new Date(fecha)
            }

            var cont = 1;
            while ((noches >= cont) && (cont < 365)) {
                fecha.setTime(fecha.getTime() + (86400000));
                if (fecha.getHours() == 1) fecha.setTime(fecha.getTime() - 3600000);
                else if (fecha.getHours() == 23) fecha.setTime(fecha.getTime() + 3600000);
                cont++;
            }
            return fecha;
        }

        $( function() {

            $('#id_fecha_de_inicio').datepicker({
                dateFormat: "yy-mm-dd",
                minDate: new Date(),
                defaultDate: new Date(),
                onSelect: function (date) {
                    $('#id_fecha_de_fin').datepicker('option', 'minDate',  sumar_noches(date, 1));
                }
            });

            $('#id_fecha_de_fin').datepicker({
                dateFormat: "yy-mm-dd",
                onSelect: function (date) {
                    console.log(date)
                }
            });
        });
    </script>

{% endblock js %}

templates/works/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div id="content-wrapper">
    {% url 'work:list-exprired' as url_work %}
    {% if url_work == request.path %}
    <h1>Contratos con multa </h1><br><br>
    {% endif %}

    {% url 'work:list-vigentes' as url_work %}
    {% if url_work == request.path %}
    <h1>Contratos al día<a class="fas fa-fw fa-plus-circle" href="{% url 'work:create' %}"></a></h1><br><br>
    {% endif %}

    {% url 'work:list-finished' as url_work %}
    {% if url_work == request.path %}
    <h1>Contratos finalizados</h1><br><br>
    {% endif %}

    <div id="accordion" class="accordion central_container_accordion">
        {% for work in object_list %}
        <div class="card">
            <div class="card-header" id="heading-{{ work.id }}">
                <h5 class="mb-0" data-toggle="collapse" data-target="#collapse-{{ work.id }}" aria-expanded="true"
                    aria-controls="collapse-{{ work.id }}">
                    {{ work.nombre }}
                </h5>
            </div>

            <div id="collapse-{{ work.id }}" class="collapse {% if forloop.first %}show{% endif %}"
                aria-labelledby="heading-{{ work.id }}" data-parent="#accordion">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">Nombre de la obra: {{ work.nombre }}</li>
                    <li class="list-group-item">Dirección: {{ work.direccion }}</li>
                    <li class="list-group-item">Tipo de obra: {{ work.tipo }}</li>
                    <li class="list-group-item">Valor: {{ work.valor }}</li>
                    {% if work.multa %}
                    <li class="list-group-item">Multa: {{ work.multa }}</li>
                    {% endif %}
                    {% url 'work:list-finished' as url_work %}
                    {% if url_work == request.path %}
                    <li class="list-group-item">Multa: {{ work.multa }}</li>
                    {% endif %}
                    <li class="list-group-item">Fecha de inicio: {{ work.fecha_de_inicio }}</li>
                    <li class="list-group-item">Fecha de fin: {{ work.fecha_de_fin }}</li>
                    <li class="list-group-item">Estado: {{ work.mostrar_estado }}</li>
                    <li class="list-group-item">Contratista: {{ work.contratista }}</li>
                    <li class="list-group-item">regla: {{ work.reglas }}</li>

                </ul>
                <div class="card-body">
                    {% if request.user.is_staff %}
                        {% url 'work:list-finished' as url_work %}
                        {% if not url_work == request.path %}
                        <a href="#FinalizarModal-{{ work.id }}" class="btn btn-success" data-toggle="modal">
                            Finalizar
                        </a>
                        {% endif %}

                        <a href="{% url 'work:report' work.id %}" class="btn btn-warning">Informe</a>
                        <a href="{% url 'work:update' work.id %}" class="btn btn-primary">Modificar</a>                        

                        {% url 'work:list-finished' as url_work %}
                        {% if not url_work == request.path %}
                        <a href="{% url 'work:delete' work.id %}" class="btn btn-danger">Eliminar</a>
                        {% endif %}
                    {% endif %}
                    

                </div>

            </div>
        </div>

        <div class="modal fade" id="FinalizarModal-{{ work.id }}" tabindex="-1" role="dialog"
            aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Finalizar el contrato: {{ work.nombre }}</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item">Nombre de la obra: {{ work.nombre }}</li>
                            <li class="list-group-item">Dirección: {{ work.direccion }}</li>
                            <li class="list-group-item">Tipo de obra: {{ work.tipo }}</li>
                            <li class="list-group-item">Valor: {{ work.valor }}</li>
                            {% if work.total_multa %}
                            <li class="list-group-item">Multa: {{ work.total_multa }}</li>
                            {% endif %}
                            <li class="list-group-item">Fecha de inicio: {{ work.fecha_de_inicio }}</li>
                            <li class="list-group-item">Fecha de fin: {{ work.fecha_de_fin }}</li>
                            <li class="list-group-item">Estado: {{ work.mostrar_estado }}</li>
                            <li class="list-group-item">Contratista: {{ work.contratista }}</li>
                            <li class="list-group-item">regla: {{ work.reglas }}</li>

                        </ul>
                    </div>
                    <div class="modal-footer">
                        <form action="{% url 'work:finish' work.id %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="estado" value="false">
                            <button type="submit" class="btn btn-primary">Aceptar</button>
                        </form>

                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                    </div>
                </div>
            </div>
        </div>

        {% empty %}
        <div class="jumbotron jumbotron-fluid">
            <div class="container">
                <h1 class="display-4">No se han encontrado datos.</h1>
                <p class="lead">Verifique haber creado la firma de un contrato antes.</p>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock content %}

{% block js %}
{{ block.super }}
{% endblock js %}

templates/works/update.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div id="content-wrapper">
    <h1>Modificar contratos <a class="fas fa-fw fa-list-ul" href="{% url 'work:list-vigentes' %}"></a></h1><br><br>
    <form class="central_container_form needs-validation was-validatedx" action="{% url 'work:update' object.id %}"
        method="POST">
        {% csrf_token %}
        <!--<div class="">
                <h1 id="exampleModalLabel">Agregar contratista</h1>
            </div>-->
        {% for hidden in form.hidden_fields %}
        {{ hidden }}
        {% endfor %}
        {% for field in form.visible_fields %}
        <div
            class="form-group  {% if field.name == 'fecha_de_inicio' or field.name == 'fecha_de_fin' %}date dp-date{% endif %}">
            {{ field.label_tag }}
            {{ field }}
            {% if field.name == 'fecha_de_inicio' or field.name == 'fecha_de_fin' %}
            <span class="input-group-addon"></span>
            {% endif %}
            {% for error in field.errors %}
            <div class="invalid-feedback">
                {{ error }}
            </div>
            {% endfor %}
        </div>
        {% endfor %}
        <div class="modal-footer">
            <a href="#ModificarModal-{{ work.id }}" class="btn btn-primary" data-toggle="modal">
                Modificar
            </a>
            <a href="{% url 'work:list-vigentes' %}" class="btn btn-secondary">Cancelar</a>
        </div>

        <div class="modal fade" id="ModificarModal-{{ work.id }}" tabindex="-1" role="dialog"
            aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Modificar el contrato: {{ work.nombre}}</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <p>¿Esta seguro de modificar este contrato?</p>
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-primary">Aceptar</button>
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock content %}

{% block js %}
{{ block.super }}
<script src="{% static '/js/sb-admin.min.js' %}"></script>

<script type="text/javascript">
    function sumar_noches(fecha, noches) {

        if (!(fecha instanceof Date)) {
            fecha = new Date(fecha)
        }

        var cont = 1;
        while ((noches >= cont) && (cont < 365)) {
            fecha.setTime(fecha.getTime() + (86400000));
            if (fecha.getHours() == 1) fecha.setTime(fecha.getTime() - 3600000);
            else if (fecha.getHours() == 23) fecha.setTime(fecha.getTime() + 3600000);
            cont++;
        }
        return fecha;
    }

    $(function () {

        $('#id_fecha_de_inicio').datepicker({
            dateFormat: "yy-mm-dd",
            minDate: new Date(),
            defaultDate: new Date(),
            onSelect: function (date) {
                $('#id_fecha_de_fin').datepicker('option', 'minDate', sumar_noches(date, 1));
            }
        });

        $('#id_fecha_de_fin').datepicker({
            dateFormat: "yy-mm-dd",
            onSelect: function (date) {
                console.log(date)
            }
        });
    });
</script>
{% endblock js %}